import { Product } from '@/types/product';
import { PromoCode } from '@/types/cart';
import { ShippingMethodOption, UserProfile } from '@/types/user';
import { CurrencyCode, CurrencyConfig } from '@/types/currency';

export const CURRENCIES: Record<CurrencyCode, CurrencyConfig> = {
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    flag: '🇺🇸',
    rate: 1.0,
    format: (amount) => `$${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    flag: '🇪🇺',
    rate: 0.92,
    format: (amount) => `€${(amount * 0.92).toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    flag: '🇬🇧',
    rate: 0.78,
    format: (amount) => `£${(amount * 0.78).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  JPY: {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen',
    flag: '🇯🇵',
    rate: 154.0,
    format: (amount) => `¥${Math.round(amount * 154).toLocaleString('ja-JP')}`,
  },
  CAD: {
    code: 'CAD',
    symbol: 'CA$',
    name: 'Canadian Dollar',
    flag: '🇨🇦',
    rate: 1.36,
    format: (amount) => `CA$${(amount * 1.36).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  INR: {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    flag: '🇮🇳',
    rate: 86.5,
    format: (amount) => `₹${Math.round(amount * 86.5).toLocaleString('en-IN')}`,
  },
  AUD: {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar',
    flag: '🇦🇺',
    rate: 1.54,
    format: (amount) => `A$${(amount * 1.54).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
};

export const PROMO_CODES: Record<string, PromoCode> = {
  WELCOME10: {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 0.1,
    description: '10% off your entire JudesCart order',
  },
  JUDES20: {
    code: 'JUDES20',
    discountType: 'percentage',
    discountValue: 0.2,
    description: '20% off all department selections',
  },
  SAVE50: {
    code: 'SAVE50',
    discountType: 'fixed',
    discountValue: 50,
    description: '$50 off orders over $250',
  },
  LUCKY25: {
    code: 'LUCKY25',
    discountType: 'percentage',
    discountValue: 0.25,
    description: '25% off your entire order (Lucky Draw Grand Prize!)',
  },
  LUCKY20: {
    code: 'LUCKY20',
    discountType: 'percentage',
    discountValue: 0.2,
    description: '20% off all department selections (Lucky Draw Prize)',
  },
  WELCOME15: {
    code: 'WELCOME15',
    discountType: 'percentage',
    discountValue: 0.15,
    description: '15% off your order - Welcome Bonus',
  },
  TECHBONUS: {
    code: 'TECHBONUS',
    discountType: 'percentage',
    discountValue: 0.15,
    description: '15% off electronics and tech gear',
  },
  MYSTERY10: {
    code: 'MYSTERY10',
    discountType: 'percentage',
    discountValue: 0.1,
    description: '10% off + Complimentary Mystery Gift with delivery',
  },
  LUCKY50: {
    code: 'LUCKY50',
    discountType: 'fixed',
    discountValue: 50,
    description: '$50 off orders over $200 (Lucky Draw Voucher)',
  },
  FREESHIP: {
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 15,
    description: 'Free Express Courier Shipping ($15 value)',
  },
};

export const SHIPPING_METHODS: ShippingMethodOption[] = [
  {
    id: 'standard',
    name: 'JudesCart Standard Ground Delivery',
    estimatedDays: '3–5 Business Days',
    price: 0,
    description: 'Complimentary carbon-neutral shipping on orders over $99',
  },
  {
    id: 'express',
    name: 'JudesCart Express Air',
    estimatedDays: '2 Business Days',
    price: 15,
    description: 'Priority courier with real-time GPS parcel tracking',
  },
  {
    id: 'overnight',
    name: 'JudesCart White-Glove Overnight',
    estimatedDays: 'Next Day Delivery',
    price: 25,
    description: 'Next-day priority delivery with signature confirmation',
  },
];

export const PRODUCTS: Product[] = [
  // 1. ELECTRONICS
  {
    id: 'prod-elec-01',
    slug: 'sonicpro-wireless-noise-cancelling-headphones',
    name: 'SonicPro Wireless ANC Studio Headphones',
    tagline: 'Custom 40mm beryllium acoustic drivers with adaptive noise cancellation',
    description: 'Engineered for audiophiles and remote professionals. Delivers pristine acoustic clarity, deep sub-bass response, ultra-plush memory foam earcups, and up to 45 hours of continuous battery life.',
    category: 'electronics',
    brand: 'JUDES',
    profit: 850,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 299,
    originalPrice: 349,
    rating: 4.93,
    reviewCount: 142,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Matte Space Black', hex: '#1C1C1C', imageIndex: 0 },
      { name: 'Silver Platinum', hex: '#E5E7EB', imageIndex: 1 },
      { name: 'Midnight Navy', hex: '#1E3A8A', imageIndex: 2 },
    ],
    sizes: [
      { name: 'Standard Fit', stock: 28 },
    ],
    details: {
      materials: 'Anodized aluminum arms, soft protein leather ear cushions, titanium drivers',
      origin: 'Acoustic engineering in Munich, Germany',
      care: 'Wipe down earcups with dry microfiber cloth. Store in included hardshell case.',
      sustainability: '100% recycled aluminum frame, plastic-free paper pulp packaging.',
    },
    reviews: [
      {
        id: 'rev-e1',
        author: 'David Rodriguez',
        rating: 5,
        date: '2 days ago',
        title: 'Better than Sony and Bose combined',
        comment: 'The soundstage is wide and airy. The noise cancellation completely silences coffee shops and flights. Best tech purchase of the year.',
        verified: true,
        helpfulCount: 38,
      },
    ],
  },
  {
    id: 'prod-elec-02',
    slug: 'auraglow-smart-ambient-desk-lamp',
    name: 'AuraGlow Smart Ambient Desk Lamp & Qi Charger',
    tagline: 'Circadian rhythm lighting with fast 15W wireless device charging',
    description: 'Sleek brushed brass and matte black desk lamp that syncs with natural daylight patterns to boost focus and reduce eye strain. Features a seamless wireless induction charging pad built into the solid weighted base.',
    category: 'electronics',
    brand: 'AuraGlow Tech',
    profit: 380,
    drawTier: 'gold',
    isBumperEligible: false,
    price: 149,
    originalPrice: 180,
    rating: 4.86,
    reviewCount: 54,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Brushed Brass / Black', hex: '#C29B38', imageIndex: 0 },
      { name: 'Matte White Ceramic', hex: '#F9FAFB', imageIndex: 1 },
    ],
    sizes: [
      { name: 'Compact (14")', stock: 15 },
      { name: 'Full Size (18")', stock: 9 },
    ],
    details: {
      materials: 'Aviation-grade aluminum, anti-glare diffuser, fast Qi inductive coil',
      origin: 'Designed in Copenhagen, Denmark',
      care: 'Dust with soft dry cloth. Disconnect power before cleaning.',
      sustainability: 'Energy-star certified 50,000-hour LED diodes.',
    },
    reviews: [
      {
        id: 'rev-e2',
        author: 'Hannah Lee',
        rating: 5,
        date: '1 week ago',
        title: 'Completely elevated my WFH desk setup',
        comment: 'Charges my phone right on the base while providing warm, calming light. Incredible build quality.',
        verified: true,
        helpfulCount: 19,
      },
    ],
  },

  // 2. APPAREL
  {
    id: 'prod-01',
    slug: 'cashmere-oversized-cardigan',
    name: 'The Mongolian Cashmere Cardigan',
    tagline: 'Pure 2-ply grade-A cashmere with horn buttons',
    description: 'Crafted from ethically sourced Mongolian cashmere fibers known for unmatched softness and thermal regulation. Designed with a relaxed drop-shoulder silhouette, ribbed cuffs, and custom horn-embossed buttons.',
    category: 'apparel',
    brand: 'JUDES',
    profit: 920,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 340,
    originalPrice: 420,
    rating: 4.9,
    reviewCount: 48,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Oatmeal Melange', hex: '#D7CEC7', imageIndex: 0 },
      { name: 'Obsidian Black', hex: '#1E1E1E', imageIndex: 1 },
      { name: 'Eucalyptus Sage', hex: '#8E9B90', imageIndex: 2 },
    ],
    sizes: [
      { name: 'XS', stock: 5 },
      { name: 'S', stock: 12 },
      { name: 'M', stock: 8 },
      { name: 'L', stock: 3 },
      { name: 'XL', stock: 0 },
    ],
    details: {
      materials: '100% Grade-A Mongolian Cashmere (7-gauge knit)',
      origin: 'Knit in Biella, Italy',
      care: 'Hand wash cold or dry clean gently. Lay flat to dry on towel.',
      sustainability: 'OEKO-TEX Certified, 100% biodegradable regenerative yarn.',
    },
    reviews: [
      {
        id: 'rev-1',
        author: 'Elena Vance',
        rating: 5,
        date: '3 days ago',
        title: 'Heirloom quality knitwear',
        comment: 'The weight and drape are exceptional. It feels weightless yet keeps me completely warm in cold breezes.',
        verified: true,
        helpfulCount: 19,
      },
    ],
  },
  {
    id: 'prod-06',
    slug: 'tailored-wool-cocoon-coat',
    name: 'The Oversized Double-Breasted Cocoon Coat',
    tagline: '100% virgin Melton wool with cupro lining',
    description: 'An architectural winter staple with dropped shoulders, sharp peak lapels, and deep welt pockets. Engineered to provide warmth down to -10°C with an effortless silhouette.',
    category: 'apparel',
    brand: 'JUDES',
    profit: 1450,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 680,
    originalPrice: 790,
    rating: 4.92,
    reviewCount: 19,
    badge: 'Limited Edition',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Camel Heather', hex: '#C19A6B', imageIndex: 0 },
      { name: 'Deep Navy', hex: '#1C2833', imageIndex: 1 },
      { name: 'Pitch Black', hex: '#111111', imageIndex: 0 },
    ],
    sizes: [
      { name: '36 FR / 2 US', stock: 2 },
      { name: '38 FR / 4 US', stock: 4 },
      { name: '40 FR / 6 US', stock: 3 },
      { name: '42 FR / 8 US', stock: 0 },
    ],
    details: {
      materials: '100% Heavy Virgin Melton Wool (650g/m²), 100% Bemberg Cupro lining',
      origin: 'Crafted in Lyon, France',
      care: 'Specialist dry clean only. Steam gently.',
      sustainability: 'Responsible Wool Standard (RWS) certified ethical shearing.',
    },
    reviews: [
      {
        id: 'rev-7',
        author: 'Charlotte Lindqvist',
        rating: 5,
        date: '3 weeks ago',
        title: 'The coat of a lifetime',
        comment: 'The weight of the virgin wool makes it hang like a sculptural masterpiece. Perfection.',
        verified: true,
        helpfulCount: 16,
      },
    ],
  },

  // 3. LEATHER GOODS
  {
    id: 'prod-02',
    slug: 'structured-tote-cognac',
    name: 'The Sella Structured Leather Tote',
    tagline: 'Full-grain Tuscan calfskin with brushed brass hardware',
    description: 'An architectural everyday tote that commands elegance. Features seamless bridle leather handles, an interior padded 15-inch laptop compartment, and protective base studs.',
    category: 'leather-goods',
    brand: 'JUDES',
    profit: 1100,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 490,
    rating: 4.85,
    reviewCount: 34,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Cognac Brown', hex: '#8B4513', imageIndex: 0 },
      { name: 'Midnight Onyx', hex: '#111111', imageIndex: 1 },
      { name: 'Chalk White', hex: '#F0ECE1', imageIndex: 0 },
    ],
    sizes: [
      { name: 'One Size', stock: 9 },
    ],
    details: {
      materials: 'Vegetable-tanned full-grain Italian calfskin with micro-suede lining',
      origin: 'Handcrafted in Florence, Italy',
      care: 'Condition annually with natural beeswax balm. Keep away from prolonged rain.',
      sustainability: 'Zero chromium tanning, sourced from ethical food-byproduct farms.',
    },
    reviews: [
      {
        id: 'rev-3',
        author: 'Sophia Chen',
        rating: 5,
        date: '1 week ago',
        title: 'My everyday work grail',
        comment: 'Fits my 15" MacBook Pro, charger, water bottle, and notebook with room to spare without losing its shape.',
        verified: true,
        helpfulCount: 14,
      },
    ],
  },

  // 4. FOOTWEAR
  {
    id: 'prod-03',
    slug: 'minimalist-chelsea-boot',
    name: 'The Atelier Lugged Chelsea Boot',
    tagline: 'Waterproof waxed suede with lightweight Vibram sole',
    description: 'An elevated interpretation of the traditional Chelsea boot. Handcrafted with waxed weatherproof suede, elasticated tonal gussets, and an ultra-lightweight treaded sole.',
    category: 'footwear',
    brand: 'JUDES',
    profit: 460,
    drawTier: 'gold',
    isBumperEligible: true,
    price: 380,
    originalPrice: 440,
    rating: 4.8,
    reviewCount: 29,
    badge: 'Sale',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Espresso Suede', hex: '#3E2723', imageIndex: 0 },
      { name: 'Dune Sand', hex: '#BCAAA4', imageIndex: 1 },
    ],
    sizes: [
      { name: '39 EU / 6 US', stock: 3 },
      { name: '40 EU / 7 US', stock: 6 },
      { name: '41 EU / 8 US', stock: 11 },
      { name: '42 EU / 9 US', stock: 4 },
      { name: '43 EU / 10 US', stock: 0 },
      { name: '44 EU / 11 US', stock: 2 },
    ],
    details: {
      materials: 'Waterproof waxed calf suede, Vibram Vi-Lite rubber outsole',
      origin: 'Porto, Portugal',
      care: 'Brush with brass suede brush. Treat with hydrophobic spray periodically.',
      sustainability: 'Recycled rubber compound in outsole, REACH-compliant leather.',
    },
    reviews: [
      {
        id: 'rev-4',
        author: 'Julian Moreau',
        rating: 5,
        date: '5 days ago',
        title: 'Walked 15 miles in NYC zero break-in period',
        comment: 'Incredible comfort right out of the box. Got compliments on the subway twice in the first week.',
        verified: true,
        helpfulCount: 22,
      },
    ],
  },

  // 5. HOME & LIVING
  {
    id: 'prod-04',
    slug: 'botanical-sculpted-candle',
    name: 'Hesperis Botanical Scented Candle',
    tagline: 'Wild bergamot, black pepper, and smokey cedarwood',
    description: 'Poured by hand into a matte fluted ceramic vessel. Features a double unbleached cotton wick and a formulation of pure coconut and rapeseed wax for a clean 65-hour burn.',
    category: 'home-living',
    brand: 'Hesperis Living',
    profit: 140,
    drawTier: 'silver',
    isBumperEligible: false,
    price: 85,
    rating: 4.95,
    reviewCount: 62,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Matte Sandstone', hex: '#E0D5C1', imageIndex: 0 },
      { name: 'Charcoal Terra', hex: '#374151', imageIndex: 1 },
    ],
    sizes: [
      { name: '300g / 10.5 oz', stock: 24 },
    ],
    details: {
      materials: '100% Botanical Rapeseed & Coconut wax, Lead-free cotton wicks',
      origin: 'Grasse, France',
      care: 'Trim wick to 5mm before each lighting. Burn for minimum 2 hours on first light.',
      sustainability: 'Reusable ceramic vessel, zero paraffin, cruelty-free fragrance oils.',
    },
    reviews: [
      {
        id: 'rev-5',
        author: 'Camille Dubois',
        rating: 5,
        date: '1 month ago',
        title: 'Transforms the entire room',
        comment: 'Not overpowering at all, just subtle and luxurious like a 5-star Parisian boutique hotel.',
        verified: true,
        helpfulCount: 31,
      },
    ],
  },
  {
    id: 'prod-07',
    slug: 'japanese-ceramic-pour-over-set',
    name: 'Hasami Ceramic Brewer & Server',
    tagline: 'Matte porcelain clay with natural oak coaster',
    description: 'Modern Japanese minimalism meets ritual morning coffee. Made using traditional 400-year-old Hasami pottery methods blending crushed stone and unglazed clay.',
    category: 'home-living',
    brand: 'Hasami Crafts',
    profit: 190,
    drawTier: 'silver',
    isBumperEligible: false,
    price: 135,
    rating: 4.88,
    reviewCount: 41,
    badge: 'New',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Unglazed Natural Clay', hex: '#D2B48C', imageIndex: 0 },
      { name: 'Gloss White Ash', hex: '#F8F9F9', imageIndex: 1 },
    ],
    sizes: [
      { name: '600ml Server', stock: 18 },
    ],
    details: {
      materials: 'Hasami porcelain and crushed volcanic stone',
      origin: 'Nagasaki Prefecture, Japan',
      care: 'Dishwasher and microwave safe. Handle with gentle care.',
      sustainability: 'Hand-thrown local natural materials, zero toxic glazes.',
    },
    reviews: [
      {
        id: 'rev-8',
        author: 'Liam O’Connor',
        rating: 5,
        date: '1 month ago',
        title: 'Elevated morning ritual',
        comment: 'Not only does it brew fantastic coffee with standard V60 filters, it looks like modern sculpture on my counter.',
        verified: true,
        helpfulCount: 12,
      },
    ],
  },

  // 6. BEAUTY & WELLNESS
  {
    id: 'prod-05',
    slug: 'restorative-botanical-serum',
    name: 'Solis Cellular Replenish Oil',
    tagline: 'Cold-pressed Marula, Sea Buckthorn, and Rosehip',
    description: 'A nutrient-dense facial nectar that restores epidermal radiance and moisture retention. Absorbs instantly with a non-greasy satin finish and a natural wild blossom aroma.',
    category: 'beauty',
    brand: 'JUDES',
    profit: 220,
    drawTier: 'silver',
    isBumperEligible: true,
    price: 110,
    rating: 4.9,
    reviewCount: 88,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Golden Amber Bottle', hex: '#E5A642', imageIndex: 0 },
    ],
    sizes: [
      { name: '30ml / 1.0 fl oz', stock: 35 },
      { name: '50ml / 1.7 fl oz', stock: 15 },
    ],
    details: {
      materials: 'Cold-pressed organic Sclerocarya Birrea (Marula), Hippophae Rhamnoides (Sea Buckthorn)',
      origin: 'Formulated in Kyoto, Japan',
      care: 'Store in a cool dry space out of direct sunlight. Press 3-4 drops gently into clean skin.',
      sustainability: 'Packaged in miron violet glass to block UV radiation and prolong bio-potency.',
    },
    reviews: [
      {
        id: 'rev-6',
        author: 'Aria Takahashi',
        rating: 5,
        date: '2 weeks ago',
        title: 'Glass skin in a bottle',
        comment: 'My dry skin literally drank this in. No breakouts, just plump dewy skin all morning.',
        verified: true,
        helpfulCount: 45,
      },
    ],
  },

  // 7. NEW PRODUCTS: ELECTRONICS
  {
    id: 'prod-elec-03',
    slug: 'solis-pro-spatial-wireless-earbuds',
    name: 'Solis Pro Spatial Audio Wireless Earbuds',
    tagline: 'Dual balanced armature drivers with 3D head-tracking spatial audio',
    description: 'Ultra-compact titanium wireless earbuds with hybrid noise-cancellation and transparency passthrough. Powered by beryllium micro-drivers for deep bass and crystal acoustic vocals.',
    category: 'electronics',
    brand: 'JUDES',
    profit: 580,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 199,
    originalPrice: 249,
    rating: 4.91,
    reviewCount: 76,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Titanium Grey', hex: '#64748B', imageIndex: 0 },
      { name: 'Arctic White', hex: '#F8FAFC', imageIndex: 1 },
    ],
    sizes: [
      { name: 'Standard Case + 4 Tips', stock: 45 },
    ],
    details: {
      materials: 'Aerospace-grade titanium alloy, medical-grade silicone ear tips',
      origin: 'Designed in Zurich, Switzerland',
      care: 'Keep contacts clean with dry lint-free cloth. IPX5 water resistant.',
      sustainability: '100% recycled aluminum charging case.',
    },
    reviews: [
      {
        id: 'rev-e3',
        author: 'Nate Gallagher',
        rating: 5,
        date: '3 days ago',
        title: 'Unbelievable soundstage',
        comment: 'The spatial audio positioning in live concerts is mesmerizing. Battery lasts forever.',
        verified: true,
        helpfulCount: 22,
      },
    ],
  },
  {
    id: 'prod-elec-04',
    slug: 'vanguard-mechanical-custom-keyboard',
    name: 'Vanguard Ultra-Slim Custom Mechanical Keyboard',
    tagline: 'Hot-swappable low-profile switches with wireless multi-device pairing',
    description: 'CNC machined solid aluminum body with factory-lubricated Gateron tactile switches. Seamlessly connects across Mac, Windows, and iPad with zero latency 2.4GHz and Bluetooth 5.3.',
    category: 'electronics',
    brand: 'KeyCraft Atelier',
    profit: 320,
    drawTier: 'gold',
    isBumperEligible: false,
    price: 159,
    originalPrice: 189,
    rating: 4.88,
    reviewCount: 42,
    badge: 'Bestseller',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Space Slate', hex: '#1E293B', imageIndex: 0 },
      { name: 'Moonlight Silver', hex: '#E2E8F0', imageIndex: 1 },
    ],
    sizes: [
      { name: '75% Compact Layout', stock: 18 },
      { name: '100% Full Size', stock: 12 },
    ],
    details: {
      materials: '6063 Anodized Aluminum, PBT Dye-Sub Keycaps',
      origin: 'Seoul, South Korea',
      care: 'Clean with keyboard brush or compressed air. Avoid liquid spills.',
      sustainability: 'Repairable modular switch architecture engineered for 10-year lifespan.',
    },
    reviews: [
      {
        id: 'rev-e4',
        author: 'Kenji Sato',
        rating: 5,
        date: '5 days ago',
        title: 'Typing bliss',
        comment: 'The acoustic dampening foam gives the deepest, cleanest marble sound. Stunning anodization.',
        verified: true,
        helpfulCount: 17,
      },
    ],
  },

  // 8. NEW PRODUCTS: APPAREL
  {
    id: 'prod-app-03',
    slug: 'merino-wool-minimalist-overshirt',
    name: 'The Meridian Merino Wool Utility Overshirt',
    tagline: 'Dense 320gsm Australian Merino wool with horn buttons',
    description: 'A structural layering overshirt designed for temperate transitions. Features dual expandable chest pockets, concealed placket closures, and a softly brushed thermal interior.',
    category: 'apparel',
    brand: 'JUDES',
    profit: 780,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 280,
    originalPrice: 320,
    rating: 4.93,
    reviewCount: 31,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Charcoal Melange', hex: '#262626', imageIndex: 0 },
      { name: 'Dark Olive', hex: '#3B4434', imageIndex: 1 },
    ],
    sizes: [
      { name: 'S', stock: 8 },
      { name: 'M', stock: 14 },
      { name: 'L', stock: 10 },
      { name: 'XL', stock: 6 },
    ],
    details: {
      materials: '100% Extra-fine Australian Merino Wool',
      origin: 'Biella, Northern Italy',
      care: 'Dry clean or spot wash with wool detergent.',
      sustainability: 'Responsible Wool Standard certified, non-mulesed wool.',
    },
    reviews: [
      {
        id: 'rev-a3',
        author: 'Liam Vance',
        rating: 5,
        date: '4 days ago',
        title: 'Impeccable drape and warmth',
        comment: 'Substantial weight that drapes effortlessly over a tee or knitwear. My favorite shirt this season.',
        verified: true,
        helpfulCount: 11,
      },
    ],
  },
  {
    id: 'prod-app-04',
    slug: 'relaxed-tailored-linen-trouser',
    name: 'The Riviera Relaxed French Linen Trousers',
    tagline: '100% Normandy flax linen with deep double front pleats',
    description: 'Breezy yet impeccably tailored trousers cut with a wide leg, subtle taper, and adjustable side tabs. Keeps you remarkably cool in high humidity with understated resort poise.',
    category: 'apparel',
    brand: 'Sartorial Studio',
    profit: 210,
    drawTier: 'silver',
    isBumperEligible: false,
    price: 165,
    originalPrice: 195,
    rating: 4.84,
    reviewCount: 24,
    badge: 'New',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Sand Ecru', hex: '#E5DFD3', imageIndex: 0 },
      { name: 'Navy Stone', hex: '#1E293B', imageIndex: 1 },
    ],
    sizes: [
      { name: '30W / 32L', stock: 6 },
      { name: '32W / 32L', stock: 9 },
      { name: '34W / 32L', stock: 7 },
      { name: '36W / 32L', stock: 3 },
    ],
    details: {
      materials: '100% Pure Normandy Flax Linen (240gsm)',
      origin: 'Normandy, France',
      care: 'Machine wash delicate cold. Hang dry, warm iron if desired.',
      sustainability: 'GOTS-certified European flax cultivated with zero irrigation.',
    },
    reviews: [
      {
        id: 'rev-a4',
        author: 'Mateo Rossi',
        rating: 5,
        date: '1 week ago',
        title: 'Perfect summer trousers',
        comment: 'The drape of this French linen is unmatched. Pairs beautifully with loafers or clean sneakers.',
        verified: true,
        helpfulCount: 9,
      },
    ],
  },

  // 9. NEW PRODUCTS: FOOTWEAR
  {
    id: 'prod-foot-03',
    slug: 'monochrome-leather-court-sneakers',
    name: 'The Artisan Minimalist Court Sneaker',
    tagline: 'Hand-stitched Tuscan Napa leather with recycled rubber cupsole',
    description: 'The definitive monochrome court sneaker. Built with butter-soft calfskin leather lining, memory foam supportive footbed, and waxed Italian cotton laces.',
    category: 'footwear',
    brand: 'JUDES',
    profit: 490,
    drawTier: 'gold',
    isBumperEligible: true,
    price: 220,
    originalPrice: 260,
    rating: 4.92,
    reviewCount: 65,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Triple White', hex: '#FAFAFA', imageIndex: 0 },
      { name: 'Onyx Monochrome', hex: '#111111', imageIndex: 1 },
    ],
    sizes: [
      { name: '40 EU / 7 US', stock: 5 },
      { name: '41 EU / 8 US', stock: 12 },
      { name: '42 EU / 9 US', stock: 15 },
      { name: '43 EU / 10 US', stock: 8 },
      { name: '44 EU / 11 US', stock: 4 },
    ],
    details: {
      materials: 'Full-grain Italian Napa calfskin, Margom-style rubber cupsole',
      origin: 'Civitanova Marche, Italy',
      care: 'Wipe with damp cloth and apply neutral leather lotion.',
      sustainability: 'Gold-rated Leather Working Group (LWG) certified tannery.',
    },
    reviews: [
      {
        id: 'rev-f3',
        author: 'Alexandre Dumas',
        rating: 5,
        date: '6 days ago',
        title: 'Better than Common Projects',
        comment: 'Leather is noticeably softer out of the box, zero blisters on first wear. Outstanding craftsmanship.',
        verified: true,
        helpfulCount: 28,
      },
    ],
  },
  {
    id: 'prod-foot-04',
    slug: 'handcrafted-calfskin-penny-loafer',
    name: 'The Verano Handcrafted Goodyear Welt Loafers',
    tagline: 'Full-grain French box calfskin with double oak-bark leather sole',
    description: 'Timeless penny loafer silhouette engineered with a traditional Goodyear welt for lifelong recraftability. Hand-burnished finish delivers rich tonal depth.',
    category: 'footwear',
    brand: 'Artisan Shoe Works',
    profit: 620,
    drawTier: 'platinum',
    isBumperEligible: false,
    price: 340,
    originalPrice: 395,
    rating: 4.89,
    reviewCount: 38,
    badge: 'Limited Edition',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Oxblood Cordovan', hex: '#4A1525', imageIndex: 0 },
      { name: 'Espresso Calf', hex: '#2C1B18', imageIndex: 1 },
    ],
    sizes: [
      { name: '40 EU / 7 US', stock: 3 },
      { name: '41 EU / 8 US', stock: 6 },
      { name: '42 EU / 9 US', stock: 9 },
      { name: '43 EU / 10 US', stock: 4 },
      { name: '44 EU / 11 US', stock: 2 },
    ],
    details: {
      materials: 'French box calf leather, Goodyear welt construction, oak-bark tanned leather outsole',
      origin: 'Northampton, England',
      care: 'Condition with Saphir Renovateur and use cedar shoe trees.',
      sustainability: '100% repairable welted footwear built to last decades.',
    },
    reviews: [
      {
        id: 'rev-f4',
        author: 'Oliver Bennett',
        rating: 5,
        date: '2 weeks ago',
        title: 'Heirloom level footwear',
        comment: 'The last shape is sleek yet accommodates the foot naturally. Incredible leather quality.',
        verified: true,
        helpfulCount: 15,
      },
    ],
  },

  // 10. NEW PRODUCTS: LEATHER GOODS
  {
    id: 'prod-leath-03',
    slug: 'voyager-leather-weekender-duffel',
    name: 'The Voyager Full-Grain Leather Weekender Duffel',
    tagline: 'Solid brass YKK Excella zippers with reinforced bridle straps',
    description: 'The quintessential travel companion for 3 to 5 day voyages. Handcrafted from supple vegetable-tanned leather that patinas gorgeously over years of globetrotting.',
    category: 'leather-goods',
    brand: 'JUDES',
    profit: 1350,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 520,
    originalPrice: 590,
    rating: 4.96,
    reviewCount: 52,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Heritage Tan', hex: '#A0522D', imageIndex: 0 },
      { name: 'Pitch Onyx', hex: '#111111', imageIndex: 1 },
    ],
    sizes: [
      { name: '45L Cabin Approved', stock: 12 },
    ],
    details: {
      materials: 'Full-grain Tuscan bridle leather, Japanese YKK Excella brass hardware, waterproof cotton canvas lining',
      origin: 'Florence, Italy',
      care: 'Condition with natural leather wax every 6 months.',
      sustainability: 'Hand-dyed with plant-derived vegetable tannins.',
    },
    reviews: [
      {
        id: 'rev-l3',
        author: 'Sebastian King',
        rating: 5,
        date: '5 days ago',
        title: 'The ultimate travel bag',
        comment: 'Flew transatlantic twice already. Fits easily in overhead bins and looks more handsome every trip.',
        verified: true,
        helpfulCount: 31,
      },
    ],
  },
  {
    id: 'prod-leath-04',
    slug: 'minimalist-bifold-card-holder',
    name: 'The Slim Fold Calfskin Cardholder & Money Clip',
    tagline: 'Beveled and hand-burnished edges with RFID protective mesh',
    description: 'Designed to eliminate pocket bulk. Features 6 card slots, a center bill compartment, and an integrated solid brass spring clip holding up to 15 folded banknotes.',
    category: 'leather-goods',
    brand: 'JUDES',
    profit: 180,
    drawTier: 'silver',
    isBumperEligible: true,
    price: 85,
    originalPrice: 110,
    rating: 4.88,
    reviewCount: 67,
    badge: 'Sale',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Caramel Saddle', hex: '#C68B59', imageIndex: 0 },
      { name: 'Forest Green', hex: '#1E3A2F', imageIndex: 1 },
    ],
    sizes: [
      { name: 'Ultra-Slim 8mm Profile', stock: 30 },
    ],
    details: {
      materials: 'Vegetable-tanned Buttero leather from Conceria Walpier',
      origin: 'Tuscany, Italy',
      care: 'Buff lightly with dry cloth.',
      sustainability: 'Zero chemical toxins, biodegradable natural leather.',
    },
    reviews: [
      {
        id: 'rev-l4',
        author: 'Daniel Craig',
        rating: 5,
        date: '1 week ago',
        title: 'Front pocket perfection',
        comment: 'Edges are burnished like glass. Holds 8 cards and cash with barely any thickness.',
        verified: true,
        helpfulCount: 18,
      },
    ],
  },

  // 11. NEW PRODUCTS: HOME & LIVING
  {
    id: 'prod-home-03',
    slug: 'hasami-matte-ceramic-coffee-ritual-set',
    name: 'The Hasami Ceramic Pour-Over & Gooseneck Kettle Set',
    tagline: 'Handmade porcelain-clay blend with precision flow gooseneck spout',
    description: 'Transform daily coffee preparation into an art form. Includes a 600ml temperature-controlled gooseneck kettle, Hasami porcelain dripper, and two stackable stoneware mugs.',
    category: 'home-living',
    brand: 'Atelier Terra',
    profit: 340,
    drawTier: 'gold',
    isBumperEligible: false,
    price: 140,
    originalPrice: 165,
    rating: 4.94,
    reviewCount: 47,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Matte Charcoal Clay', hex: '#2B2D2F', imageIndex: 0 },
      { name: 'Sandstone Beige', hex: '#D8CAB8', imageIndex: 1 },
    ],
    sizes: [
      { name: 'Complete 4-Piece Set', stock: 22 },
    ],
    details: {
      materials: 'Natural Hasami porcelain clay, food-grade 304 stainless steel interior',
      origin: 'Hasami, Nagasaki, Japan',
      care: 'Ceramics are dishwasher and microwave safe. Hand wash kettle.',
      sustainability: 'Sourced from local crushed Amakusa pottery stones.',
    },
    reviews: [
      {
        id: 'rev-h3',
        author: 'Mina Tanaka',
        rating: 5,
        date: '4 days ago',
        title: 'Mindful mornings',
        comment: 'The texture of the matte unglazed exterior feels earthy and warm in hands. Pour control is flawless.',
        verified: true,
        helpfulCount: 25,
      },
    ],
  },

  // 12. NEW PRODUCTS: BEAUTY & WELLNESS
  {
    id: 'prod-beauty-02',
    slug: 'botanical-renewal-elixir-gua-sha-kit',
    name: 'The Empress Botanical Renewal Elixir & Rose Quartz Gua Sha',
    tagline: 'Infused with Bakuchiol, Blue Tansy, and hand-carved Brazilian quartz',
    description: 'An Ayurvedic and TCM inspired facial ritual. Combines concentrated botanical squalane and Blue Tansy with a master-carved rose quartz gua sha tool to stimulate lymphatic drainage and firm contours.',
    category: 'beauty',
    brand: 'JUDES',
    profit: 260,
    drawTier: 'gold',
    isBumperEligible: true,
    price: 115,
    originalPrice: 135,
    rating: 4.95,
    reviewCount: 63,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1608248597359-bb43efb6be57?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Rose Quartz & Indigo Bottle', hex: '#E29578', imageIndex: 0 },
    ],
    sizes: [
      { name: '50ml Elixir + Sculptor Tool', stock: 25 },
    ],
    details: {
      materials: 'Natural Brazilian Rose Quartz, Cold-pressed Blue Tansy, Plant Squalane, Bakuchiol',
      origin: 'Formulated in Provence, France',
      care: 'Clean stone with mild soap and warm water. Store oil away from sunlight.',
      sustainability: 'Cruelty-free, vegan certified, recyclable glass container.',
    },
    reviews: [
      {
        id: 'rev-b2',
        author: 'Isla Montgomery',
        rating: 5,
        date: '1 week ago',
        title: 'Instant facial lift',
        comment: 'The blue tansy soothes any redness immediately, and the heavy quartz stone feels icy cold and soothing.',
        verified: true,
        helpfulCount: 29,
      },
    ],
  },
];

export const INITIAL_USER: UserProfile = {
  name: 'Eleanor Sterling',
  email: 'eleanor.sterling@judes-cart.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  savedAddresses: [
    {
      firstName: 'Eleanor',
      lastName: 'Sterling',
      email: 'eleanor.sterling@judes-cart.com',
      phone: '+1 (555) 234-8910',
      street: '742 Evergreen Terrace',
      apartment: 'Apt 4B',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94107',
      country: 'United States',
    },
  ],
  orders: [
    {
      id: 'JC-82910',
      date: 'Aug 24, 2026',
      items: [
        {
          id: 'prod-elec-01-black-std',
          productId: 'prod-elec-01',
          name: 'SonicPro Wireless ANC Studio Headphones',
          image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80',
          color: 'Matte Space Black',
          size: 'Standard Fit',
          price: 299,
          quantity: 1,
        },
      ],
      subtotal: 299,
      discount: 0,
      shipping: 0,
      tax: 25.42,
      total: 324.42,
      currency: 'USD',
      shippingAddress: {
        firstName: 'Eleanor',
        lastName: 'Sterling',
        email: 'eleanor.sterling@judes-cart.com',
        phone: '+1 (555) 234-8910',
        street: '742 Evergreen Terrace',
        apartment: 'Apt 4B',
        city: 'San Francisco',
        state: 'CA',
        postalCode: '94107',
        country: 'United States',
      },
      shippingMethod: SHIPPING_METHODS[0],
      paymentMethod: {
        type: 'card',
        last4: '4242',
        brand: 'Visa',
      },
      status: 'Delivered',
      trackingNumber: 'JC-TRK-98234710',
      estimatedDelivery: 'Aug 28, 2026',
    },
  ],
  judesCoins: 650,
};
