import { Product } from '@/types/product';
import { PromoCode } from '@/types/cart';
import { ShippingMethodOption, UserProfile } from '@/types/user';
import { CurrencyCode, CurrencyConfig } from '@/types/currency';

export const CURRENCIES: Record<CurrencyCode, CurrencyConfig> = {
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    rate: 1.0,
    format: (amount) => `$${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    rate: 0.92,
    format: (amount) => `€${(amount * 0.92).toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    rate: 0.78,
    format: (amount) => `£${(amount * 0.78).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  JPY: {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen',
    rate: 154.0,
    format: (amount) => `¥${Math.round(amount * 154).toLocaleString('ja-JP')}`,
  },
  CAD: {
    code: 'CAD',
    symbol: 'CA$',
    name: 'Canadian Dollar',
    rate: 1.36,
    format: (amount) => `CA$${(amount * 1.36).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
  },
  INR: {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    rate: 86.5,
    format: (amount) => `₹${Math.round(amount * 86.5).toLocaleString('en-IN')}`,
  },
};

export const PROMO_CODES: Record<string, PromoCode> = {
  WELCOME10: {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 0.1,
    description: '10% off your entire JudesCart order',
  },
  JUDES20: {
    code: 'JUDES20',
    discountType: 'percentage',
    discountValue: 0.2,
    description: '20% off all department selections',
  },
  SAVE50: {
    code: 'SAVE50',
    discountType: 'fixed',
    discountValue: 50,
    description: '$50 off orders over $250',
  },
  LUCKY25: {
    code: 'LUCKY25',
    discountType: 'percentage',
    discountValue: 0.25,
    description: '25% off your entire order (Lucky Draw Grand Prize!)',
  },
  LUCKY20: {
    code: 'LUCKY20',
    discountType: 'percentage',
    discountValue: 0.2,
    description: '20% off all department selections (Lucky Draw Prize)',
  },
  WELCOME15: {
    code: 'WELCOME15',
    discountType: 'percentage',
    discountValue: 0.15,
    description: '15% off your order - Welcome Bonus',
  },
  TECHBONUS: {
    code: 'TECHBONUS',
    discountType: 'percentage',
    discountValue: 0.15,
    description: '15% off electronics and tech gear',
  },
  MYSTERY10: {
    code: 'MYSTERY10',
    discountType: 'percentage',
    discountValue: 0.1,
    description: '10% off + Complimentary Mystery Gift with delivery',
  },
  LUCKY50: {
    code: 'LUCKY50',
    discountType: 'fixed',
    discountValue: 50,
    description: '$50 off orders over $200 (Lucky Draw Voucher)',
  },
  FREESHIP: {
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 15,
    description: 'Free Express Courier Shipping ($15 value)',
  },
};

export const SHIPPING_METHODS: ShippingMethodOption[] = [
  {
    id: 'standard',
    name: 'JudesCart Standard Ground Delivery',
    estimatedDays: '3–5 Business Days',
    price: 0,
    description: 'Complimentary carbon-neutral shipping on orders over $99',
  },
  {
    id: 'express',
    name: 'JudesCart Express Air',
    estimatedDays: '2 Business Days',
    price: 15,
    description: 'Priority courier with real-time GPS parcel tracking',
  },
  {
    id: 'overnight',
    name: 'JudesCart White-Glove Overnight',
    estimatedDays: 'Next Day Delivery',
    price: 25,
    description: 'Next-day priority delivery with signature confirmation',
  },
];

export const PRODUCTS: Product[] = [
  // 1. ELECTRONICS
  {
    id: 'prod-elec-01',
    slug: 'sonicpro-wireless-noise-cancelling-headphones',
    name: 'SonicPro Wireless ANC Studio Headphones',
    tagline: 'Custom 40mm beryllium acoustic drivers with adaptive noise cancellation',
    description: 'Engineered for audiophiles and remote professionals. Delivers pristine acoustic clarity, deep sub-bass response, ultra-plush memory foam earcups, and up to 45 hours of continuous battery life.',
    category: 'electronics',
    brand: 'JUDES',
    profit: 850,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 299,
    originalPrice: 349,
    rating: 4.93,
    reviewCount: 142,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Matte Space Black', hex: '#1C1C1C', imageIndex: 0 },
      { name: 'Silver Platinum', hex: '#E5E7EB', imageIndex: 1 },
      { name: 'Midnight Navy', hex: '#1E3A8A', imageIndex: 2 },
    ],
    sizes: [
      { name: 'Standard Fit', stock: 28 },
    ],
    details: {
      materials: 'Anodized aluminum arms, soft protein leather ear cushions, titanium drivers',
      origin: 'Acoustic engineering in Munich, Germany',
      care: 'Wipe down earcups with dry microfiber cloth. Store in included hardshell case.',
      sustainability: '100% recycled aluminum frame, plastic-free paper pulp packaging.',
    },
    reviews: [
      {
        id: 'rev-e1',
        author: 'David Rodriguez',
        rating: 5,
        date: '2 days ago',
        title: 'Better than Sony and Bose combined',
        comment: 'The soundstage is wide and airy. The noise cancellation completely silences coffee shops and flights. Best tech purchase of the year.',
        verified: true,
        helpfulCount: 38,
      },
    ],
  },
  {
    id: 'prod-elec-02',
    slug: 'auraglow-smart-ambient-desk-lamp',
    name: 'AuraGlow Smart Ambient Desk Lamp & Qi Charger',
    tagline: 'Circadian rhythm lighting with fast 15W wireless device charging',
    description: 'Sleek brushed brass and matte black desk lamp that syncs with natural daylight patterns to boost focus and reduce eye strain. Features a seamless wireless induction charging pad built into the solid weighted base.',
    category: 'electronics',
    brand: 'AuraGlow Tech',
    profit: 380,
    drawTier: 'gold',
    isBumperEligible: false,
    price: 149,
    originalPrice: 180,
    rating: 4.86,
    reviewCount: 54,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Brushed Brass / Black', hex: '#C29B38', imageIndex: 0 },
      { name: 'Matte White Ceramic', hex: '#F9FAFB', imageIndex: 1 },
    ],
    sizes: [
      { name: 'Compact (14")', stock: 15 },
      { name: 'Full Size (18")', stock: 9 },
    ],
    details: {
      materials: 'Aviation-grade aluminum, anti-glare diffuser, fast Qi inductive coil',
      origin: 'Designed in Copenhagen, Denmark',
      care: 'Dust with soft dry cloth. Disconnect power before cleaning.',
      sustainability: 'Energy-star certified 50,000-hour LED diodes.',
    },
    reviews: [
      {
        id: 'rev-e2',
        author: 'Hannah Lee',
        rating: 5,
        date: '1 week ago',
        title: 'Completely elevated my WFH desk setup',
        comment: 'Charges my phone right on the base while providing warm, calming light. Incredible build quality.',
        verified: true,
        helpfulCount: 19,
      },
    ],
  },

  // 2. APPAREL
  {
    id: 'prod-01',
    slug: 'cashmere-oversized-cardigan',
    name: 'The Mongolian Cashmere Cardigan',
    tagline: 'Pure 2-ply grade-A cashmere with horn buttons',
    description: 'Crafted from ethically sourced Mongolian cashmere fibers known for unmatched softness and thermal regulation. Designed with a relaxed drop-shoulder silhouette, ribbed cuffs, and custom horn-embossed buttons.',
    category: 'apparel',
    brand: 'JUDES',
    profit: 920,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 340,
    originalPrice: 420,
    rating: 4.9,
    reviewCount: 48,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Oatmeal Melange', hex: '#D7CEC7', imageIndex: 0 },
      { name: 'Obsidian Black', hex: '#1E1E1E', imageIndex: 1 },
      { name: 'Eucalyptus Sage', hex: '#8E9B90', imageIndex: 2 },
    ],
    sizes: [
      { name: 'XS', stock: 5 },
      { name: 'S', stock: 12 },
      { name: 'M', stock: 8 },
      { name: 'L', stock: 3 },
      { name: 'XL', stock: 0 },
    ],
    details: {
      materials: '100% Grade-A Mongolian Cashmere (7-gauge knit)',
      origin: 'Knit in Biella, Italy',
      care: 'Hand wash cold or dry clean gently. Lay flat to dry on towel.',
      sustainability: 'OEKO-TEX Certified, 100% biodegradable regenerative yarn.',
    },
    reviews: [
      {
        id: 'rev-1',
        author: 'Elena Vance',
        rating: 5,
        date: '3 days ago',
        title: 'Heirloom quality knitwear',
        comment: 'The weight and drape are exceptional. It feels weightless yet keeps me completely warm in cold breezes.',
        verified: true,
        helpfulCount: 19,
      },
    ],
  },
  {
    id: 'prod-06',
    slug: 'tailored-wool-cocoon-coat',
    name: 'The Oversized Double-Breasted Cocoon Coat',
    tagline: '100% virgin Melton wool with cupro lining',
    description: 'An architectural winter staple with dropped shoulders, sharp peak lapels, and deep welt pockets. Engineered to provide warmth down to -10°C with an effortless silhouette.',
    category: 'apparel',
    brand: 'JUDES',
    profit: 1450,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 680,
    originalPrice: 790,
    rating: 4.92,
    reviewCount: 19,
    badge: 'Limited Edition',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Camel Heather', hex: '#C19A6B', imageIndex: 0 },
      { name: 'Deep Navy', hex: '#1C2833', imageIndex: 1 },
      { name: 'Pitch Black', hex: '#111111', imageIndex: 0 },
    ],
    sizes: [
      { name: '36 FR / 2 US', stock: 2 },
      { name: '38 FR / 4 US', stock: 4 },
      { name: '40 FR / 6 US', stock: 3 },
      { name: '42 FR / 8 US', stock: 0 },
    ],
    details: {
      materials: '100% Heavy Virgin Melton Wool (650g/m²), 100% Bemberg Cupro lining',
      origin: 'Crafted in Lyon, France',
      care: 'Specialist dry clean only. Steam gently.',
      sustainability: 'Responsible Wool Standard (RWS) certified ethical shearing.',
    },
    reviews: [
      {
        id: 'rev-7',
        author: 'Charlotte Lindqvist',
        rating: 5,
        date: '3 weeks ago',
        title: 'The coat of a lifetime',
        comment: 'The weight of the virgin wool makes it hang like a sculptural masterpiece. Perfection.',
        verified: true,
        helpfulCount: 16,
      },
    ],
  },

  // 3. LEATHER GOODS
  {
    id: 'prod-02',
    slug: 'structured-tote-cognac',
    name: 'The Sella Structured Leather Tote',
    tagline: 'Full-grain Tuscan calfskin with brushed brass hardware',
    description: 'An architectural everyday tote that commands elegance. Features seamless bridle leather handles, an interior padded 15-inch laptop compartment, and protective base studs.',
    category: 'leather-goods',
    brand: 'JUDES',
    profit: 1100,
    drawTier: 'platinum',
    isBumperEligible: true,
    price: 490,
    rating: 4.85,
    reviewCount: 34,
    badge: 'New',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Cognac Brown', hex: '#8B4513', imageIndex: 0 },
      { name: 'Midnight Onyx', hex: '#111111', imageIndex: 1 },
      { name: 'Chalk White', hex: '#F0ECE1', imageIndex: 0 },
    ],
    sizes: [
      { name: 'One Size', stock: 9 },
    ],
    details: {
      materials: 'Vegetable-tanned full-grain Italian calfskin with micro-suede lining',
      origin: 'Handcrafted in Florence, Italy',
      care: 'Condition annually with natural beeswax balm. Keep away from prolonged rain.',
      sustainability: 'Zero chromium tanning, sourced from ethical food-byproduct farms.',
    },
    reviews: [
      {
        id: 'rev-3',
        author: 'Sophia Chen',
        rating: 5,
        date: '1 week ago',
        title: 'My everyday work grail',
        comment: 'Fits my 15" MacBook Pro, charger, water bottle, and notebook with room to spare without losing its shape.',
        verified: true,
        helpfulCount: 14,
      },
    ],
  },

  // 4. FOOTWEAR
  {
    id: 'prod-03',
    slug: 'minimalist-chelsea-boot',
    name: 'The Atelier Lugged Chelsea Boot',
    tagline: 'Waterproof waxed suede with lightweight Vibram sole',
    description: 'An elevated interpretation of the traditional Chelsea boot. Handcrafted with waxed weatherproof suede, elasticated tonal gussets, and an ultra-lightweight treaded sole.',
    category: 'footwear',
    brand: 'JUDES',
    profit: 460,
    drawTier: 'gold',
    isBumperEligible: true,
    price: 380,
    originalPrice: 440,
    rating: 4.8,
    reviewCount: 29,
    badge: 'Sale',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Espresso Suede', hex: '#3E2723', imageIndex: 0 },
      { name: 'Dune Sand', hex: '#BCAAA4', imageIndex: 1 },
    ],
    sizes: [
      { name: '39 EU / 6 US', stock: 3 },
      { name: '40 EU / 7 US', stock: 6 },
      { name: '41 EU / 8 US', stock: 11 },
      { name: '42 EU / 9 US', stock: 4 },
      { name: '43 EU / 10 US', stock: 0 },
      { name: '44 EU / 11 US', stock: 2 },
    ],
    details: {
      materials: 'Waterproof waxed calf suede, Vibram Vi-Lite rubber outsole',
      origin: 'Porto, Portugal',
      care: 'Brush with brass suede brush. Treat with hydrophobic spray periodically.',
      sustainability: 'Recycled rubber compound in outsole, REACH-compliant leather.',
    },
    reviews: [
      {
        id: 'rev-4',
        author: 'Julian Moreau',
        rating: 5,
        date: '5 days ago',
        title: 'Walked 15 miles in NYC zero break-in period',
        comment: 'Incredible comfort right out of the box. Got compliments on the subway twice in the first week.',
        verified: true,
        helpfulCount: 22,
      },
    ],
  },

  // 5. HOME & LIVING
  {
    id: 'prod-04',
    slug: 'botanical-sculpted-candle',
    name: 'Hesperis Botanical Scented Candle',
    tagline: 'Wild bergamot, black pepper, and smokey cedarwood',
    description: 'Poured by hand into a matte fluted ceramic vessel. Features a double unbleached cotton wick and a formulation of pure coconut and rapeseed wax for a clean 65-hour burn.',
    category: 'home-living',
    brand: 'Hesperis Living',
    profit: 140,
    drawTier: 'silver',
    isBumperEligible: false,
    price: 85,
    rating: 4.95,
    reviewCount: 62,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Matte Sandstone', hex: '#E0D5C1', imageIndex: 0 },
      { name: 'Charcoal Terra', hex: '#374151', imageIndex: 1 },
    ],
    sizes: [
      { name: '300g / 10.5 oz', stock: 24 },
    ],
    details: {
      materials: '100% Botanical Rapeseed & Coconut wax, Lead-free cotton wicks',
      origin: 'Grasse, France',
      care: 'Trim wick to 5mm before each lighting. Burn for minimum 2 hours on first light.',
      sustainability: 'Reusable ceramic vessel, zero paraffin, cruelty-free fragrance oils.',
    },
    reviews: [
      {
        id: 'rev-5',
        author: 'Camille Dubois',
        rating: 5,
        date: '1 month ago',
        title: 'Transforms the entire room',
        comment: 'Not overpowering at all, just subtle and luxurious like a 5-star Parisian boutique hotel.',
        verified: true,
        helpfulCount: 31,
      },
    ],
  },
  {
    id: 'prod-07',
    slug: 'japanese-ceramic-pour-over-set',
    name: 'Hasami Ceramic Brewer & Server',
    tagline: 'Matte porcelain clay with natural oak coaster',
    description: 'Modern Japanese minimalism meets ritual morning coffee. Made using traditional 400-year-old Hasami pottery methods blending crushed stone and unglazed clay.',
    category: 'home-living',
    brand: 'Hasami Crafts',
    profit: 190,
    drawTier: 'silver',
    isBumperEligible: false,
    price: 135,
    rating: 4.88,
    reviewCount: 41,
    badge: 'New',
    isFeatured: false,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Unglazed Natural Clay', hex: '#D2B48C', imageIndex: 0 },
      { name: 'Gloss White Ash', hex: '#F8F9F9', imageIndex: 1 },
    ],
    sizes: [
      { name: '600ml Server', stock: 18 },
    ],
    details: {
      materials: 'Hasami porcelain and crushed volcanic stone',
      origin: 'Nagasaki Prefecture, Japan',
      care: 'Dishwasher and microwave safe. Handle with gentle care.',
      sustainability: 'Hand-thrown local natural materials, zero toxic glazes.',
    },
    reviews: [
      {
        id: 'rev-8',
        author: 'Liam O’Connor',
        rating: 5,
        date: '1 month ago',
        title: 'Elevated morning ritual',
        comment: 'Not only does it brew fantastic coffee with standard V60 filters, it looks like modern sculpture on my counter.',
        verified: true,
        helpfulCount: 12,
      },
    ],
  },

  // 6. BEAUTY & WELLNESS
  {
    id: 'prod-05',
    slug: 'restorative-botanical-serum',
    name: 'Solis Cellular Replenish Oil',
    tagline: 'Cold-pressed Marula, Sea Buckthorn, and Rosehip',
    description: 'A nutrient-dense facial nectar that restores epidermal radiance and moisture retention. Absorbs instantly with a non-greasy satin finish and a natural wild blossom aroma.',
    category: 'beauty',
    brand: 'JUDES',
    profit: 220,
    drawTier: 'silver',
    isBumperEligible: true,
    price: 110,
    rating: 4.9,
    reviewCount: 88,
    badge: 'Bestseller',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=85',
    ],
    colors: [
      { name: 'Golden Amber Bottle', hex: '#E5A642', imageIndex: 0 },
    ],
    sizes: [
      { name: '30ml / 1.0 fl oz', stock: 35 },
      { name: '50ml / 1.7 fl oz', stock: 15 },
    ],
    details: {
      materials: 'Cold-pressed organic Sclerocarya Birrea (Marula), Hippophae Rhamnoides (Sea Buckthorn)',
      origin: 'Formulated in Kyoto, Japan',
      care: 'Store in a cool dry space out of direct sunlight. Press 3-4 drops gently into clean skin.',
      sustainability: 'Packaged in miron violet glass to block UV radiation and prolong bio-potency.',
    },
    reviews: [
      {
        id: 'rev-6',
        author: 'Aria Takahashi',
        rating: 5,
        date: '2 weeks ago',
        title: 'Glass skin in a bottle',
        comment: 'My dry skin literally drank this in. No breakouts, just plump dewy skin all morning.',
        verified: true,
        helpfulCount: 45,
      },
    ],
  },
];

export const INITIAL_USER: UserProfile = {
  name: 'Eleanor Sterling',
  email: 'eleanor.sterling@judes-cart.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  savedAddresses: [
    {
      firstName: 'Eleanor',
      lastName: 'Sterling',
      email: 'eleanor.sterling@judes-cart.com',
      phone: '+1 (555) 234-8910',
      street: '742 Evergreen Terrace',
      apartment: 'Apt 4B',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94107',
      country: 'United States',
    },
  ],
  orders: [
    {
      id: 'JC-82910',
      date: 'Aug 24, 2026',
      items: [
        {
          id: 'prod-elec-01-black-std',
          productId: 'prod-elec-01',
          name: 'SonicPro Wireless ANC Studio Headphones',
          image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80',
          color: 'Matte Space Black',
          size: 'Standard Fit',
          price: 299,
          quantity: 1,
        },
      ],
      subtotal: 299,
      discount: 0,
      shipping: 0,
      tax: 25.42,
      total: 324.42,
      currency: 'USD',
      shippingAddress: {
        firstName: 'Eleanor',
        lastName: 'Sterling',
        email: 'eleanor.sterling@judes-cart.com',
        phone: '+1 (555) 234-8910',
        street: '742 Evergreen Terrace',
        apartment: 'Apt 4B',
        city: 'San Francisco',
        state: 'CA',
        postalCode: '94107',
        country: 'United States',
      },
      shippingMethod: SHIPPING_METHODS[0],
      paymentMethod: {
        type: 'card',
        last4: '4242',
        brand: 'Visa',
      },
      status: 'Delivered',
      trackingNumber: 'JC-TRK-98234710',
      estimatedDelivery: 'Aug 28, 2026',
    },
  ],
};
